app:
    resource: "@AppBundle/Controller/"
    type:     annotation

battles:
    resource: AppBundle\Controller\BattleController
    type:     rest

registration:
    resource: AppBundle\Controller\RegistrationController
    type:     rest
