app:
    resource: "@AppBundle/Controller/"
    type:     annotation

battles:
    resource: AppBundle\Controller\BattleController
    type:     rest

user:
    resource:  AppBundle\Controller\UserController
    type:      rest

logout:
    path:   /logout/
